; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
build_flags = 
    -DFASTLED_ALL_PINS_HARDWARE_SPI
    -DFASTLED_ESP32_SPI_BUS=FSPI
	'-D ARDUINO_USB_CDC_ON_BOOT=1'
lib_deps =
    ;https://github.com/coryking/FastLED.git#esp32s3-fix
lib_extra_dirs=/Users/coryking/projects/FastLED

[env:seeed_xiao_esp32s3]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_flags = ${env.build_flags} -O3 -ffast-math -finline-functions -funroll-loops
upload_port=/dev/cu.usbmodem2101
monitor_port=/dev/cu.usbmodem2101



[env:lolin_s3_mini_debug]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_flags = 
    ${env.build_flags} 
    -DCORE_DEBUG_LEVEL=5     
    -ggdb
    -gdwarf-4
    -fvar-tracking-assignments
    -fno-omit-frame-pointer
    -Og
    -g3  
    -save-temps=obj
upload_port=/dev/cu.usbmodem2101
monitor_port=/dev/cu.usbmodem2101
debug_tool = esp-builtin
debug_init_break = break setup
build_type = debug      ;build in debug mode instead of release mode