// PWM-to-RPM Calibration Table
// Generated by scripts/calibration_model.py
// Encoder positions 0-40 mapped to target RPM range 700-2900
// Format: {encoder_position, pwm_percent, estimated_rpm}

struct CalibrationPoint {
    uint8_t encoder_position;
    uint8_t pwm_percent;
    uint16_t estimated_rpm;
};

const CalibrationPoint CALIBRATION_TABLE[41] = {
    { 0,   0,    0},  // pos  0:   0% PWM -> ~   0 RPM
    { 1,  55,  697},  // pos  1:  55% PWM -> ~ 697 RPM
    { 2,  56,  755},  // pos  2:  56% PWM -> ~ 755 RPM
    { 3,  56,  812},  // pos  3:  56% PWM -> ~ 812 RPM
    { 4,  57,  869},  // pos  4:  57% PWM -> ~ 869 RPM
    { 5,  57,  925},  // pos  5:  57% PWM -> ~ 925 RPM
    { 6,  58,  982},  // pos  6:  58% PWM -> ~ 982 RPM
    { 7,  58, 1037},  // pos  7:  58% PWM -> ~1037 RPM
    { 8,  59, 1093},  // pos  8:  59% PWM -> ~1093 RPM
    { 9,  59, 1147},  // pos  9:  59% PWM -> ~1147 RPM
    {10,  60, 1213},  // pos 10:  60% PWM -> ~1213 RPM
    {11,  60, 1267},  // pos 11:  60% PWM -> ~1267 RPM
    {12,  61, 1320},  // pos 12:  61% PWM -> ~1320 RPM
    {13,  61, 1374},  // pos 13:  61% PWM -> ~1374 RPM
    {14,  62, 1437},  // pos 14:  62% PWM -> ~1437 RPM
    {15,  62, 1489},  // pos 15:  62% PWM -> ~1489 RPM
    {16,  63, 1541},  // pos 16:  63% PWM -> ~1541 RPM
    {17,  64, 1603},  // pos 17:  64% PWM -> ~1603 RPM
    {18,  64, 1664},  // pos 18:  64% PWM -> ~1664 RPM
    {19,  65, 1714},  // pos 19:  65% PWM -> ~1714 RPM
    {20,  65, 1775},  // pos 20:  65% PWM -> ~1775 RPM
    {21,  66, 1824},  // pos 21:  66% PWM -> ~1824 RPM
    {22,  66, 1883},  // pos 22:  66% PWM -> ~1883 RPM
    {23,  67, 1942},  // pos 23:  67% PWM -> ~1942 RPM
    {24,  68, 1999},  // pos 24:  68% PWM -> ~1999 RPM
    {25,  68, 2057},  // pos 25:  68% PWM -> ~2057 RPM
    {26,  69, 2113},  // pos 26:  69% PWM -> ~2113 RPM
    {27,  69, 2169},  // pos 27:  69% PWM -> ~2169 RPM
    {28,  70, 2225},  // pos 28:  70% PWM -> ~2225 RPM
    {29,  71, 2280},  // pos 29:  71% PWM -> ~2280 RPM
    {30,  71, 2334},  // pos 30:  71% PWM -> ~2334 RPM
    {31,  72, 2388},  // pos 31:  72% PWM -> ~2388 RPM
    {32,  72, 2450},  // pos 32:  72% PWM -> ~2450 RPM
    {33,  73, 2502},  // pos 33:  73% PWM -> ~2502 RPM
    {34,  74, 2563},  // pos 34:  74% PWM -> ~2563 RPM
    {35,  74, 2614},  // pos 35:  74% PWM -> ~2614 RPM
    {36,  75, 2673},  // pos 36:  75% PWM -> ~2673 RPM
    {37,  76, 2731},  // pos 37:  76% PWM -> ~2731 RPM
    {38,  76, 2789},  // pos 38:  76% PWM -> ~2789 RPM
    {39,  77, 2845},  // pos 39:  77% PWM -> ~2845 RPM
    {40,  78, 2901},  // pos 40:  78% PWM -> ~2901 RPM
};